### PR TITLE
fixed issue #1 now it works same as  console.log 👓 🕶👓 🕶

### PR DESCRIPTION
**Pull request by Aniket965**
- [x] fixed log function to take multiple arguments as a message string and separate them with a blank space , same as console.log function ,this is #1 issue

### CODE REVIEW

**Comment by Aniket965** [comment]
Actually for using spread operator , in function definition spread operator should be used as last argument. , So have to change code from above and i run standard --fix

**Comment by Aniket965** [comment]
final code looks like this
```javascript
 function log (type = '', ...msg) {
   const timestamp = new Date().toTimeString().split(' ')[0]
   const isDebug = config.debug
   let icon = ''
   switch (type) {
     case 'info':
       icon = '📄'
       break
     case 'error':
       icon = '💥'
       break
     case 'warn':
       icon = '⚠️'
       break
     case 'debug':
       icon = '🐛'
       break
     default:
   }

   if (['error', 'info', 'warn', 'debug'].indexOf(type) === -1) {
     msg.unshift(type)
   }
   if (type.toLowerCase() !== 'debug' || isDebug) {
     console.log(`[${timestamp}] ${icon}\t${msg.join(' ')}`)
   }
 }

 // register types
 ['error', 'info', 'warn', 'debug'].forEach(type => {
   log[type] = (...msg) => log(type, ...msg)
 })

 module.exports = {
   log
 }

````

**Comment by Aniket965** [comment]
image

for testing i checked it up on console

**Comment by anoff** [comment]
The complete `logger.js` file has an indentation of 1 space. This isn't right. Not sure what happened with the `--fix` but please make sure that the base indentation is 0.

image

**Comment by Aniket965** [comment]
is that fine  ?now

**Pull request merged**
